language: scala
scala:
  - 2.11.12
  #- 2.12.8
  # holden's library not yet for 2.12
sudo: required
dist: trusty
group: edge

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete