language: scala
scala:
  - 2.11.12
  #- 2.12.8
  # holden's library not yet for 2.12
sudo: required
dist: trusty
group: edge

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: test
      script:
        - sbt scalafmtCheck
        - sbt test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete